FROM oven/bun:1-slim AS base

WORKDIR /app

COPY package.json ./

RUN bun install --frozen-lockfile

COPY . .

ENV NODE_ENV=production \
    PORT=3000 \
    NEXT_TELEMETRY_DISABLED=1

RUN bun run build

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs --ingroup nodejs
USER nextjs

EXPOSE 3000

CMD ["bun", "run", "start"]